root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'player.index'
        permanent: true

controllers:
    resource:
        path: ../src/
        namespace: App\
    type: attribute
