# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

parameters:
  audios_folder: '%env(resolve:AUDIOS_FOLDER)%'
  covers_folder: '%env(resolve:COVERS_FOLDER)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $projectDir: '%kernel.project_dir%'
      $audiosFolder: '%audios_folder%'
      $coversFolder: '%covers_folder%'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Player/Application/Player/AudioPlayingStarted.php'
      - '../src/Player/Application/Player/AudioPlayingStopped.php'


  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  Mhor\MediaInfo\MediaInfo: ~

  player.async:
    class: 'App\Player\Infrastructure\AsyncPlayer'

  App\Player\Application\Interactor\PlayerInterface: '@player.async'

  App\WebUI\PlayerController:
    tags:
      - { name: kernel.event_subscriber }
